name: Pipeline Sonar + EcoSonar
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test-analyze:
    name: Build, Test, SonarQube & EcoSonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test with coverage
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadless

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Setup Python for EcoSonar
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install EcoSonar dependencies
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/Accenture/EcoSonar.git
          cd EcoSonar
          pip install -r requirements.txt

      - name: Run EcoSonar
        run: |
          cd EcoSonar
          python eco_sonar.py ../src --output-format markdown > ../eco-report.md
        continue-on-error: true

      - name: Upload EcoSonar report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: eco-report
          path: eco-report.md
